local harpoon = require("harpoon")

keybind("n", "<M-m>", function()
	harpoon:list():add()
end, "Mark buffer"):register()
keybind("n", "<M-u>", function()
	harpoon:list():remove()
end, "Unmark buffer"):register()
keybind("n", "<M-e>", function()
	harpoon.ui:toggle_quick_menu(harpoon:list(), { border = "rounded" })
end, "Explore marks"):register()
keybind("n", "<M-l>", function()
	harpoon:list():next({ ui_nav_wrap = true })
end, "Next mark"):register()
keybind("n", "<M-h>", function()
	harpoon:list():prev({ ui_nav_wrap = true })
end, "Previous mark"):register()
