plugin("smoka7/hop.nvim"):event("VeryLazy"):config(function()
	local hop = require("hop")
	hop.setup({})

	keybind("n", "F", function()
		local current_oil_dir = require("oil").get_current_dir()
		if current_oil_dir == nil then
			vim.cmd("HopWord")
		else
			vim.cmd("HopLine")
		end
	end, "Jump to word"):register()
	keybind("v", "F", "<cmd>HopLine<cr>", "Jump to line"):register()
	keybind("n", "gl", "<cmd>HopLine<cr>", "Jump to line"):register()
	keybind({ "n", "v" }, "gf", "<cmd>HopChar1<cr>", "Global jump to char"):register()
	keybind({ "n", "v" }, "f", function()
		hop.hint_char1({ current_line_only = true })
	end, "Jump to char"):register()
	keybind({ "n", "v" }, "t", function()
		hop.hint_char1({ current_line_only = true, hint_offset = -1 })
	end, "Jump before char"):register()
end)
plugin("christoomey/vim-tmux-navigator"):event("VeryLazy"):config(function()
	keybind("n", "<C-h>", "<cmd>TmuxNavigateLeft<CR>", "Navigate window left")
	keybind("n", "<C-j>", "<cmd>TmuxNavigateDown<CR>", "Navigate window down")
	keybind("n", "<C-k>", "<cmd>TmuxNavigateUp<CR>", "Navigate window up")
	keybind("n", "<C-l>", "<cmd>TmuxNavigateRight<CR>", "Navigate window right")
end)
plugin("ThePrimeagen/harpoon")
	:branch("harpoon2")
	:dependencies("nvim-lua/plenary.nvim")
	:event("VeryLazy")
	:config(function()
		local harpoon = require("harpoon")
		keybind("n", "<M-m>", function()
			harpoon:list():add()
		end, "Mark buffer"):register()
		keybind("n", "<M-u>", function()
			harpoon:list():remove()
		end, "Unmark buffer"):register()
		keybind("n", "<M-e>", function()
			harpoon.ui:toggle_quick_menu(harpoon:list(), { border = "rounded" })
		end, "Explore marks"):register()
		keybind("n", "<M-l>", function()
			harpoon:list():next({ ui_nav_wrap = true })
		end, "Next mark"):register()
		keybind("n", "<M-h>", function()
			harpoon:list():prev({ ui_nav_wrap = true })
		end, "Previous mark"):register()
	end)
