{
  pkgs,
  vim_pkgs,
  nvim_pkgs,
  ...
}: {
  lspsAndRuntimeDeps = with pkgs; [
    sqlite
    vscode-json-languageserver
    yaml-language-server
    helm-ls
    prettierd
    tofu-ls
    tflint
    dockerfile-language-server
    docker-language-server
    docker-compose-language-service
    jdt-language-server
    java-debug
    codelldb
    ty
    uv
    fd
    ruff
    just-lsp
  ];
  startupPlugins = with vim_pkgs; [
    lze
    lzextras
    plenary-nvim
    nvim-nio
    promise-async
    pkgs.unstable.vimPlugins.SchemaStore-nvim
  ];

  optionalPlugins = with nvim_pkgs; [
    which-key
    lspconfig
    oil
    oil-vcs
    tokyonight
    snacks
    tmux-navigation
    hop
    blink-compat
    blink-cmp-git
    blink-cmp-conventional-commits
    tabout
    nvim-surround
    mini-ai
    mini-move
    nvim-treesitter-endwise
    nvim-treesitter-textobjects
    treesitter-context
    conform
    lint
    osc52
    smart-paste
    treesj
    scrollbar
    undotree
    nvim-dap
    nvim-dap-ui
    nvim-dap-virtual-text
    copilot
    opencode
    todo-comments
    exrc
    overseer
    ufo
    cutlass
    multicursor-nvim
    live-command
    grug-far
    trouble
    quicker
    smart-splits
    neotest
    neotest-golang
    neogen
    luasnip
    visual-whitespace
    yaml_nvim
    jdtls
    venv-selector
    dap-python
    pkgs.unstable.vimPlugins.blink-cmp
    pkgs.unstable.vimPlugins.blink-pairs
    pkgs.unstable.vimPlugins.blink-indent
    pkgs.unstable.vimPlugins.nvim-treesitter.withAllGrammars
    pkgs.unstable.vimPlugins.nvim-dbee
  ];
}
