{
  pkgs,
  vim_pkgs,
  nvim_pkgs,
  ...
}: {
  lspsAndRuntimeDeps = with pkgs; [
    sqlite
    fd
    ast-grep
    curl
    grpcurl

    # db cli
    mysql84
  ];
  startupPlugins = with vim_pkgs; [
    lze
    lzextras
    plenary-nvim
    nvim-nio
    promise-async
    SchemaStore-nvim
  ];

  optionalPlugins = with nvim_pkgs; [
    atlas
    which-key
    lspconfig
    fyler
    tokyonight
    snacks
    tmux-navigation
    hop
    marks
    blink-compat
    blink-cmp-git
    blink-cmp-conventional-commits
    tabout
    mini-surround
    mini-ai
    mini-move
    nvim-treesitter-endwise
    nvim-treesitter-textobjects
    origami
    treesitter-context
    conform
    lint
    osc52
    smart-paste
    treesj
    scrollbar
    undotree
    nvim-dap
    nvim-dap-ui
    nvim-dap-virtual-text
    opencode
    oil
    oil-git
    todo-comments
    exrc
    overseer
    cutlass
    dadbod
    dbab
    live-command
    grug-far
    trouble
    quicker
    smart-splits
    neotest
    neogen
    luasnip
    visual-whitespace
    startuptime
    puppeteer
    onoma
    vim_pkgs.blink-cmp
    vim_pkgs.blink-pairs
    vim_pkgs.blink-indent
    vim_pkgs.nvim-treesitter.withAllGrammars
    vim_pkgs.kulala-nvim
  ];
}
